spring:
  application:
    name: mab-file-uploader
  servlet:
    multipart:
      max-file-size: 100MB   # Set your desired maximum file size here
      max-request-size: 100MB  # Set the maximum request size here if needed
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    url: ${DB_URL:jdbc:postgresql://localhost:5434/mab_manitos_db}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

minio:
  url: ${MINIO_SERVER_URI:http://localhost:9000}
  access:
    key: ${MINIO_ACCESS_KEY:fRPjAS1XQXjpLjgT1eFp}
    secret: ${MINIO_SECRET_KEY:I8hoMgLRRpkkcCIC9CmNsv8ZmUxuYEH5ezv0TJrE}