spring:
  application:
    name: mab-file-uploader
  servlet:
    multipart:
      max-file-size: 100MB   # Set your desired maximum file size here
      max-request-size: 100MB  # Set the maximum request size here if needed
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${DB_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

minio:
  url: ${MINIO_SERVER_URI:http://192.241.149.226:9000}
  access:
    key: ${MINIO_ACCESS_KEY:s9hMvQP8oWmsyBSSGVpn}
    secret: ${MINIO_SECRET_KEY:bIp3EPP0GfJjUtGOpUy8pYcb7sDNidVXdvB9s6fG}


management:
  tracing:
    sampling:
      probability: 1.0
#logging:
#  pattern:
#    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'